### ISSUE TITLE
problem help please

### ISSUE THREAD

**Issue by kerenbir** [lytves/ETH-balance-bot#2]
i got this massage while try to run it

```
Traceback (most recent call last):
  File "ethdroidbot.py", line 9, in <module>
    from ethdroid.handlers import start, admin_say, error, text_handler, scheduler_balance_changes_check
  File "/home/bitnami/ETHdroidBot/ethdroid/handlers.py", line 6, in <module>
    import ethdroid.utils as utils
  File "/home/bitnami/ETHdroidBot/ethdroid/utils.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
can you help please...

**Comment by K4LITE** [comment]
pip install requests

Try this
